#Name of the application
spring:
  application:
    name: ZuulService

#Gateway Port
server:
  port: 8900
     
#Routing Endpoints
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    skill-microservice:
      url: http://localhost:8961

    search-microservice:
      url: http://localhost:8962

    user-microservice:
      url: http://localhost:8963

    training-microservice:
      url: http://localhost:8964

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
